title: "CLEF 2025 SimpleText" 
email: "contact@simpletext-project.com"
description: >-
  SimpleText is a track organized as part of the
  <a href="https://clef2025.clef-initiative.eu/index.php" style="color: #4682B4; font-weight: bold;">
  CLEF 2025 conference</a>, initiated by the 
  <a href="http://www.clef-initiative.eu/" style="color: #4682B4; font-weight: bold;">CLEF initiative</a>.
url: "http://simpletext-project.com/2024/en/"
twitter_username: "SimpletextW"
github_username: "simpletext-madics"

# Theme and plugins
remote_theme: "pages-themes/slate@v0.2.0"
plugins:
  - jekyll-remote-theme
