    <link rel="stylesheet" href="styles.css">
title: "CLEF 2025 SimpleText"
email: contact@simpletext-project.com
description: "SimpleText est une piste organisée dans le cadre de la conférence CLEF 2025."
url: "https://simpletext-project.com"
baseurl: ""  # Pas de sous-répertoire, site à la racine
theme: "pages-themes/slate@v0.2.0"

# Configuration des plugins
plugins:
  - jekyll-remote-theme

# Réseaux sociaux
twitter_username: "SimpletextW"
github_username: "simpletext-madics"

# Menu personnalisé
menu:
  - title: "Accueil"
    url: "/"
  - title: "Program"
    url: "/program"
  - title: "CFP"
    url: "/cfp"
  - title: "Dates"
    url: "/dates"
  - title: "Contact"
    url: "/contact"

# Paramètres personnalisés
social:
  twitter: "https://twitter.com/SimpletextW"
  github: "https://github.com/simpletext-madics"
